-- =====================================================
-- Project: Digital Marketing Customer Segmentation
-- File: 04_revenue_by_source.sql
--
-- Business Question:
-- Which traffic sources generate the highest revenue?
--
-- Business Importance:
-- Traffic volume alone does not measure marketing success.
-- This analysis identifies which acquisition channels
-- contribute the most revenue, helping marketers allocate
-- budgets more effectively.
--
-- SQL Concepts Used:
-- • STRUCT fields (trafficSource.source)
-- • SUM()
-- • IFNULL()
-- • GROUP BY
-- • ORDER BY
-- • Column Aliases (AS)
--
-- Expected Insight:
-- Compare revenue generated by each traffic source.
-- Identify high-value marketing channels that generate
-- more revenue rather than simply more visitors.
-- =====================================================

SELECT
    trafficSource.source AS source,
    SUM(IFNULL(totals.transactionRevenue, 0)) / 1000000 AS revenue
FROM
    `bigquery-public-data.google_analytics_sample.ga_sessions_*`
GROUP BY
    source
ORDER BY
    revenue DESC
LIMIT 15;

-- =====================================================
-- Findings
--
-- 1. Direct traffic generated the highest revenue.
-- 2. Google Search was the second-largest revenue source.
-- 3. DFA generated relatively high revenue despite fewer sessions,
--    suggesting higher-quality traffic.
-- 4. High traffic sources do not always produce the highest revenue.
-- =====================================================